### ISSUE TITLE
Error adding Stub Settings

### ISSUE THREAD

**Issue by MichaelPaulukonis** [urasandesu/Prig#21]
I'm running Windows 7 64 bit, as local admin.

I attempted the Quick Tour in both Visual Studio Professional 2012 and Visual Studio Express 2013 for Desktop, and got the same error in the PM console when attempting to add the stub settings (after first installing prig via the PM console) via `Add-PrigAssembly -Assembly "mscorlib, Version=4.0.0.0"` [full dump below],

(my actual username has been replaced with `{username}`)

I find the error `C:\Users\{username}\documents\visual studio 2013\Projects\PrigTest1\packages\Prig.0.0.0-alpha9\tools\prig.exe` to be interesting, since the `.exe` _does_ exist, but is located at either

`C:\Users\{username}\documents\visual studio 2013\Projects\PrigTest1\packages\Prig.0.0.0-alpha9\tools\x64\prig.exe` (x64 sub-dir)

or

`C:\Users\{username}\documents\visual studio 2013\Projects\PrigTest1\packages\Prig.0.0.0-alpha9\tools\x86\prig.exe` (x86 sub-dir)

```
Array assignment to [AnyCPU|true] failed: The value "" is not of type "System.Collections.Generic.List`1[System.Reflection.ProcessorArchitecture]" and cannot be used in this generic collection.
Parameter name: value.
At C:\Users\{username}\documents\visual studio 2013\Projects\PrigTest1\packages\Prig.0.0.0-alpha9\tools\Urasandesu.Prig\Urasandesu\Prig\NuGet.Add-PrigAssembly.ps1:74 char:30
+             $platformTargets[ <<<< $conditionedProperty] = New-Object 'System.Collections.Generic.List[System.Reflection.ProcessorArchitecture]'
    + CategoryInfo          : InvalidOperation: (AnyCPU|true:String) [], RuntimeException
    + FullyQualifiedErrorId : ArrayAssignmentFailed

You cannot call a method on a null-valued expression.
At C:\Users\{username}\documents\visual studio 2013\Projects\PrigTest1\packages\Prig.0.0.0-alpha9\tools\Urasandesu.Prig\Urasandesu\Prig\NuGet.Add-PrigAssembly.ps1:78 char:55
+             $platformTargets[$conditionedProperty].Add <<<< ($1stCandidateArch)
    + CategoryInfo          : InvalidOperation: (Add:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\{username}\documents\visual studio 2013\Projects\PrigTest1\packages\Prig.0.0.0-alpha9\tools\Urasandesu.Prig\Urasandesu\Prig\NuGet.Add-PrigAssembly.ps1:79 char:55
+             $platformTargets[$conditionedProperty].Add <<<< ('MSIL')
    + CategoryInfo          : InvalidOperation: (Add:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Array assignment to [AnyCPU|false] failed: The value "" is not of type "System.Collections.Generic.List`1[System.Reflection.ProcessorArchitecture]" and cannot be used in this generic collection.
Parameter name: value.
At C:\Users\{username}\documents\visual studio 2013\Projects\PrigTest1\packages\Prig.0.0.0-alpha9\tools\Urasandesu.Prig\Urasandesu\Prig\NuGet.Add-PrigAssembly.ps1:74 char:30
+             $platformTargets[ <<<< $conditionedProperty] = New-Object 'System.Collections.Generic.List[System.Reflection.ProcessorArchitecture]'
    + CategoryInfo          : InvalidOperation: (AnyCPU|false:String) [], RuntimeException
    + FullyQualifiedErrorId : ArrayAssignmentFailed

You cannot call a method on a null-valued expression.
At C:\Users\{username}\documents\visual studio 2013\Projects\PrigTest1\packages\Prig.0.0.0-alpha9\tools\Urasandesu.Prig\Urasandesu\Prig\NuGet.Add-PrigAssembly.ps1:78 char:55
+             $platformTargets[$conditionedProperty].Add <<<< ($1stCandidateArch)
    + CategoryInfo          : InvalidOperation: (Add:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\{username}\documents\visual studio 2013\Projects\PrigTest1\packages\Prig.0.0.0-alpha9\tools\Urasandesu.Prig\Urasandesu\Prig\NuGet.Add-PrigAssembly.ps1:79 char:55
+             $platformTargets[$conditionedProperty].Add <<<< ('MSIL')
    + CategoryInfo          : InvalidOperation: (Add:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Array assignment to [x64] failed: The value "" is not of type "System.Collections.Generic.List`1[System.Reflection.ProcessorArchitecture]" and cannot be used in this generic collection.
Parameter name: value.
At C:\Users\{username}\documents\visual studio 2013\Projects\PrigTest1\packages\Prig.0.0.0-alpha9\tools\Urasandesu.Prig\Urasandesu\Prig\NuGet.Add-PrigAssembly.ps1:74 char:30
+             $platformTargets[ <<<< $conditionedProperty] = New-Object 'System.Collections.Generic.List[System.Reflection.ProcessorArchitecture]'
    + CategoryInfo          : InvalidOperation: (x64:String) [], RuntimeException
    + FullyQualifiedErrorId : ArrayAssignmentFailed

You cannot call a method on a null-valued expression.
At C:\Users\{username}\documents\visual studio 2013\Projects\PrigTest1\packages\Prig.0.0.0-alpha9\tools\Urasandesu.Prig\Urasandesu\Prig\NuGet.Add-PrigAssembly.ps1:78 char:55
+             $platformTargets[$conditionedProperty].Add <<<< ($1stCandidateArch)
    + CategoryInfo          : InvalidOperation: (Add:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\{username}\documents\visual studio 2013\Projects\PrigTest1\packages\Prig.0.0.0-alpha9\tools\Urasandesu.Prig\Urasandesu\Prig\NuGet.Add-PrigAssembly.ps1:79 char:55
+             $platformTargets[$conditionedProperty].Add <<<< ('MSIL')
    + CategoryInfo          : InvalidOperation: (Add:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

The term 'C:\Users\{username}\documents\visual studio 2013\Projects\PrigTest1\packages\Prig.0.0.0-alpha9\tools\prig.exe' is not recognized as the name of a cmdlet, function, script file, or operable progra
m. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\{username}\documents\visual studio 2013\Projects\PrigTest1\packages\Prig.0.0.0-alpha9\tools\Urasandesu.Prig\Urasandesu\Prig\NuGet.Invoke-Prig.ps1:92 char:18
+                 & <<<<  $prig dasm -assembly $Assembly
    + CategoryInfo          : ObjectNotFound: (C:\Users\pauluk...\tools\prig.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

You cannot call a method on a null-valued expression.
At C:\Users\{username}\documents\visual studio 2013\Projects\PrigTest1\packages\Prig.0.0.0-alpha9\tools\Urasandesu.Prig\Urasandesu\Prig\NuGet.Add-PrigAssembly.ps1:121 char:42
+         $result.psobject.TypeNames.Insert <<<< (0, $AssemblyNameExTypeName)
    + CategoryInfo          : InvalidOperation: (Insert:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Cannot index into a null array.
At C:\Users\{username}\documents\visual studio 2013\Projects\PrigTest1\packages\Prig.0.0.0-alpha9\tools\Urasandesu.Prig\Urasandesu\Prig\NuGet.Add-PrigAssembly.ps1:108 char:53
+     SetStubSettingNoneItem $curMsbProj $actualNames[ <<<< 0] $envProj.FullName
    + CategoryInfo          : InvalidOperation: (0:Int32) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
```

**Comment by urasandesu** [comment]
Hi, long time! You are encountering same problem even now? Unfortunately, I tried to install Prig in various environments, but I had never been encountered the situation... :(  
Well, if you install Prig manually, what will become of it? Would you try the following steps?
***
1.Make a note of the install path and the tools path when executing `Install-Package Prig`.
```powershell
PM>  Install-Package Prig
# ...(snip)...
Install Path: C:\Users\Akira\Documents\Visual Studio 2013\Projects\ConsoleApplication54\packages\Prig.1.1.0
Tools Path: C:\Users\Akira\Documents\Visual Studio 2013\Projects\ConsoleApplication54\packages\Prig.1.1.0\tools
# ...(snip)...

```

2.Using the memorized information, create some variables for manual installation.
```powershell
PM>  $InstallPath = 'C:\Users\Akira\Documents\Visual Studio 2013\Projects\ConsoleApplication54\packages\Prig.1.1.0'
PM>  $ToolsPath = 'C:\Users\Akira\Documents\Visual Studio 2013\Projects\ConsoleApplication54\packages\Prig.1.1.0\tools'

```

3.Register `Urasandesu.Prig.dll` to the registry.
```powershell
PM>  regsvr32 /i ([System.IO.Path]::Combine($InstallPath, 'tools\x64\Urasandesu.Prig.dll'))
PM>  regsvr32 /i ([System.IO.Path]::Combine($InstallPath, 'tools\x86\Urasandesu.Prig.dll'))

```

4.Register this framework dlls to the GAC.
```powershell
PM>  cmd /c ('" "%VS120COMNTOOLS%VsDevCmd.bat" & gacutil /i "{0}" "' -f [System.IO.Path]::Combine($InstallPath, 'lib\net35\Urasandesu.NAnonym.dll'))
Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.33440
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly successfully added to the cache

PM>  cmd /c ('" "%VS120COMNTOOLS%VsDevCmd.bat" & gacutil /i "{0}" "' -f [System.IO.Path]::Combine($InstallPath, 'lib\net35\Urasandesu.Prig.Framework.dll'))
Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.33440
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly successfully added to the cache

PM>  cmd /c ('" "%VS120COMNTOOLS%VsDevCmd.bat" & gacutil /i "{0}" "' -f [System.IO.Path]::Combine($InstallPath, 'lib\net40\Urasandesu.NAnonym.dll'))
Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.33440
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly successfully added to the cache

PM>  cmd /c ('" "%VS120COMNTOOLS%VsDevCmd.bat" & gacutil /i "{0}" "' -f [System.IO.Path]::Combine($InstallPath, 'lib\net40\Urasandesu.Prig.Framework.dll'))
Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.33440
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly successfully added to the cache

```

5.Copy `prig.exe` to the tools path.
```powershell
PM>  Copy-Item ([System.IO.Path]::Combine($InstallPath, 'tools\x86\prig.exe')) $ToolsPath

```
***
Then, `Add-PrigAssembly` can execute successfully?

**Comment by manjunathbv** [comment]
@urasandesu  I have Visual Studio 2013 Update 5.
Wanted to try Prig and started to install the package, however getting below error in Step 2 command Add Stub Settings : "Add-PrigAssembly -Assembly "mscorlib, Version=4.0.0.0" "
Error:
Unable to find type [Microsoft.Build.Evaluation.ProjectCollection]: make sure that the assembly containing this type is loaded. At C:\Users\mvenkatarao\Documents\Essentials\Dev\Lab\TDD\Moking\packages\Prig.1.1.0\tools\Add-PrigAssembly.ps1:188 char:68
+ $msbProjCollection = [Microsoft.Build.Evaluation.ProjectCollection] <<<< ::GlobalProjectCollection
    + CategoryInfo          : InvalidOperation: (Microsoft.Build...ojectCollection:String) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
 
You cannot call a method on a null-valued expression. At C:\Users\mvenkatarao\Documents\Essentials\Dev\Lab\TDD\Moking\packages\Prig.1.1.0\tools\Add-PrigAssembly.ps1:190 char:45
+ $curMsbProj = $msbProjCollection.LoadProject <<<< ($ProjectFullName)
    + CategoryInfo          : InvalidOperation: (LoadProject:String) [], Runti 
   meException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
You cannot call a method on a null-valued expression.
At C:\Users\mvenkatarao\Documents\Essentials\Dev\Lab\TDD\Moking\packages\Prig.1.1.0\tools\Add-PrigAssembly.ps1:193 char:51
+ if (!$curMsbProj.ConditionedProperties.ContainsKey <<<< ('Platform')) {
    + CategoryInfo          : InvalidOperation: (ContainsKey:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
You cannot call a method on a null-valued expression.
At C:\Users\mvenkatarao\Documents\Essentials\Dev\Lab\TDD\Moking\packages\Prig.1.1.0\tools\Add-PrigAssembly.ps1:217 char:22
+ $curMsbProj.MarkDirty <<<< ()
    + CategoryInfo          : InvalidOperation: (MarkDirty:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
The term 'C:\Users\mvenkatarao\Documents\Essentials\Dev\Lab\TDD\Moking\packages\Prig.1.1.0\tools\prig.exe' is not recognized as the name of a cmdlet, function
, script file, or operable program. Check the spelling of the name, or if a pat
h was included, verify that the path is correct and try again.
At C:\Users\mvenkatarao\Documents\Essentials\Dev\Lab\TDD\Moking\packages\Prig.1.1.0\tools\Urasandesu.Prig\Urasandesu\Prig\NuGet.Invoke-Prig.ps1:131 char:18
+                 & <<<<  $prig dasm -assembly $Assembly
    + CategoryInfo          : ObjectNotFound: (C:\Users\mvenka...\tools\prig.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
You cannot call a method on a null-valued expression.
At C:\Users\mvenkatarao\Documents\Essentials\Dev\Lab\TDD\Moking\packages\Prig.1.1.0\tools\Urasandesu.Prig\Urasandesu\Prig\NuGet.Get-AssemblyNameExs.ps1:41 char:42
+         $result.psobject.TypeNames.Insert <<<< (0, $AssemblyNameExTypeName)
    + CategoryInfo          : InvalidOperation: (Insert:String) [], RuntimeExc 
   eption
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Assembly 'mscorlib, Version=4.0.0.0' is mismatch to the any platforms ''.

**Comment by urasandesu** [comment]
@manjunathbv Thank you for reporting the situation! This issue still don't reach the conclusion. Please accept my request, because many trial and error will probably be needed :tired_face: 
I guess you have already been tried the above steps - running VS2013 as Admin, checking GAC for MSBuild/framework and so on. Well, could you try the following operations?

### Which is the execution policy for PowerShell of your environment?
* In the Package Manager Console, execute the following command: 
```powershell
PM> Get-ExecutionPolicy
```

Usually, the result is `Bypass`. If your result is `Restricted` or `AllSigned`, it is too restrictive.

**Comment by manjunathbv** [comment]
Yes I'm running VS 2013 as Admin, This is my work laptop, so connected to Domain and Policies are driven from Domain. I tried to override it by changing values in regedit. however that dint help me. Thanks for all the help.

**Comment by urasandesu** [comment]
@manjunathbv Hmm... Could you tell me about your plugins of Visual Studio(NuGet packages, VSIX, etc...)? There is a possibly that they compete.

**Comment by urasandesu** [comment]
I closed this issue because there are no response for more than 1 year.
