### ISSUE TITLE
Using this without indirection context

### ISSUE THREAD

**Issue by LennyPenny** [urasandesu/Prig#22]
Is it possible to use this framework without having an IndirectionCotext?
I know it's there to protect you from permanently detouring functions and do other dangerous things, but that's exactly what I want to to. 
Can I achieve this with prig? Maybe even without using a test but a normal c# application. 
If it's not possible do you have any idea where I could start searching for a way to do this?

Sorry if this is the wrong place to ask btw

**Comment by urasandesu** [comment]
This issue is fixed by the correction for issue #23.
