### ISSUE TITLE
Error in remove prig assembly

### ISSUE THREAD

**Issue by wegged** [urasandesu/Prig#41]
One of my colleagues got this error when clicking the new remove prig assembly option.

![prig remove assembly error](https://cloud.githubusercontent.com/assets/3422680/7192141/dba0b976-e460-11e4-9423-6bb7dfbdfcc7.png)

**Comment by wegged** [comment]
He needed to install windows management framework 4.0.  Maybe you can add as a dependency.

**Comment by urasandesu** [comment]
Thanks for reporting! :satisfied:
I'll add the dependency information to README.md later.

**Comment by urasandesu** [comment]
Updated README.md at https://github.com/urasandesu/Prig.V2Docs/commit/13da2b214bfffa6b5fac3ed6f22422de4efdf32a

**Comment by vsix27** [comment]
I have another error during prig registration
![prig-reg-error](https://cloud.githubusercontent.com/assets/10351245/12027262/a4423a68-ad91-11e5-8fb7-928f03ad7687.png)

**Comment by vsix27** [comment]
it looks like it is impossible to integrate prig with TeamCity since prig does not use any default adapter like nunit....

**Comment by urasandesu** [comment]
@vsix27 I'm sorry, but could you create new issues? This topic is an issue in removing Prig Assembly.

You have two issues as follows, don't you?
1. Error in registering Prig
2. Support TeamCity
