### ISSUE TITLE
Add donate button

### ISSUE THREAD

**Issue by asd-and-Rizzo** [urasandesu/Prig#42]
Good project. Please add donate button somewhere.

**Comment by urasandesu** [comment]
Sorry, this is my personal project, and I am a Japanese. This means any donations between individuals are prohibited by law :expressionless:

Thanks,

**Comment by asd-and-Rizzo** [comment]
Sad:( May be there is some organization you care of to donate? I see you do progress on project, I have not time (and may be skill to help), just want to thank you for you work and motivate you keep it up to date with CoreCLR as soon as their api stabilizes.

**Comment by urasandesu** [comment]
I appreciate the thought. Japanese is prohibited donation between individuals. Nothing can be done about it, because it is law :disappointed:

By the way, of course I'm planning to support CoreCLR in the future. Please wait for that expectantly! :wink:

**Comment by urasandesu** [comment]
I have found that **the donation by gift isn't prohibited in Japan**. I don't know why it can, but it seems Japanese usual way to accept donation :sweat_smile: So, I'm going to add the button that accepts the donation by gift(e.g. Amazon Wish List).

I reopen this issue, and I will close after adding the button.

**Comment by urasandesu** [comment]
This issue is fixed by the following commit: 
423281a585ecc9f2078f1e4057187d69de4d084f
