### ISSUE TITLE
Problem Debugging unit tests

### ISSUE THREAD

**Issue by wegged** [urasandesu/Prig#43]
I am having an issue debugging unit tests that are using prig.  It causes my visual studio to crash.

Any ideas?

Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: devenv.exe
  Application Version:  12.0.31101.0
  Application Timestamp:    54548724
  Fault Module Name:    ntdll.dll
  Fault Module Version: 6.1.7601.18798
  Fault Module Timestamp:   5507b3e0
  Exception Code:   c00000fd
  Exception Offset: 0002e04e
  OS Version:   6.1.7601.2.1.0.256.4
  Locale ID:    1033
  Additional Information 1: 1b65
  Additional Information 2: 1b65fd2bc837c3f68ac38b42e645b825
  Additional Information 3: f0db
  Additional Information 4: f0db8f09d56e5f792e4047923c985d44

**Comment by urasandesu** [comment]
Thank you for the reporting :blush:

Ummm... It seems hard to tell the difference from another general Visual Studio problem. Do you always get the app crash when you attach the debugger? If you possibly can, could you tell me the steps to reproduce the problem?

**Comment by urasandesu** [comment]
I closed this issue because there are no response for more than 1 year.
