### ISSUE TITLE
Unable to add Prig assembly for mscorlib

### ISSUE THREAD

**Issue by abbeycode** [urasandesu/Prig#51]
I'm following the [walkthrough](http://urasandesu.github.io/Prig/) to get my project using Prig. It's a .Net 4.5.1 unit test, and I'm using Visual Studio 2015. When I right-click on References for the test project and click **Add Prig Assembly for mscorlib**, I get this message:

![11-16-2015 11-39-39 am](https://cloud.githubusercontent.com/assets/1349578/11187990/c6d4b7b0-8c56-11e5-8a78-ef3fae1ccc6f.png)

What should I do about this?

**Comment by abbeycode** [comment]
I added a NuGet dependency on `System.Management.Automation`, so it's now referenced from my tests project, but I still get that error.

**Comment by urasandesu** [comment]
Do you use Windows 7? Prig requires PowerShell v3.0+. If you want to use Prig in Windows 7, please install [Windows Management Framework 3.0+](https://www.microsoft.com/en-us/download/details.aspx?id=34595).

**Comment by abbeycode** [comment]
Yes, I am using Windows 7. Will I need to install the Windows Management Framework on our build servers, or is that only necessary for Visual Studio integration?

**Comment by urasandesu** [comment]
You have to do against both, because it is needed in the generating process of Prig Assembly.
