### ISSUE TITLE
Why do you use PDateTime in the sample code?

### ISSUE THREAD

**Issue by vsix27** [urasandesu/Prig#53]
your readme https://github.com/urasandesu/Prig/blob/master/README.md uses PDateTime which is not anywhere in the scope - this is your custom class i believe... - https://gist.github.com/urasandesu/8751367

having that, what is the meaning of example???:

[Test]
public void IsNowLunchBreak_should_return_false_when_11_oclock()   {
            // `IndirectionsContext` can minimize the influence of the API replacement.
            using (new IndirectionsContext())
            {
                // Arrange
                // Replace `DateTime.Now` body. Hereafter, `DateTime.Now` will return only `2013/12/13 11:00:00`.
                PDateTime.NowGet().Body = () => new DateTime(2013, 12, 13, 11, 00, 00);

```
            // Act
            var result = LifeInfo.IsNowLunchBreak();

            // Assert
            Assert.IsFalse(result);
        }
    }
```

**Comment by urasandesu** [comment]
`PDateTime` is a [Prig Type](https://github.com/urasandesu/Prig/wiki/Cheat-Sheet#-prig-typeprig-type-introducer), so it will be generated automatically based on [Stub Settings File](https://github.com/urasandesu/Prig/wiki/Cheat-Sheet#-stub-settings-file)(in QUICK TOUR case, the settings is in `mscorlib.v4.0.30319.v4.0.0.0.prig`). If you can't find the type, the auto generation has possibly failed. 

Was [the Step 3](https://github.com/urasandesu/Prig/blob/master/README.md#step-3-modify-stub-settings) success?

**Comment by urasandesu** [comment]
For your information, [the gist](https://gist.github.com/urasandesu/8751367) is just a memo for the design of [Prig Type](https://github.com/urasandesu/Prig/wiki/Cheat-Sheet#-prig-typeprig-type-introducer).
