### ISSUE TITLE
Support ILSpy

### ISSUE THREAD

**Issue by urasandesu** [urasandesu/Prig#63]
When writing the test by self-hosting, I have noticed that I usually use [ILSpy](http://ilspy.net/) to find the replacement target method. In that case, I think that Prig should support to directly get the [Indirection Stub Setting](https://github.com/urasandesu/Prig/wiki/Cheat-Sheet#indirection_stub_setting) from ILSpy, shouldn't it? 
For example, when you right click a method, a constructor and a property that is in the tree view, `Get Prig Indirection Stub Setting` menu is shown in the context menu: 
![untitled](https://cloud.githubusercontent.com/assets/291065/13904106/b593eb94-eed8-11e5-99f2-f700d9f79143.png)

Then, if you choose it, you get the effect same as when executing `Get-IndirectionStubSetting`(`pget`) command.

**Comment by urasandesu** [comment]
I have investigated the feasibility. ILSpy supports [plugins](https://github.com/icsharpcode/ILSpy/wiki/Plugins), and [CopyFullyQualifiedTypeName plugin for ILSpy](https://github.com/mdonatas/ILSpy.CopyFullyQualifiedTypeName.Plugin) has the mechanism that what I want to reference.

**Comment by urasandesu** [comment]
I created [the new repository](https://github.com/urasandesu/ILSpy.GetPrigIndirectionStubSetting.Plugin). I'm planning that it will be a Chocolatey package depending on [Prig](https://chocolatey.org/packages/Prig) and [ILSpy](https://chocolatey.org/packages/ilspy).

**Comment by urasandesu** [comment]
Now we released [the alpha version](https://github.com/urasandesu/ILSpy.GetPrigIndirectionStubSetting.Plugin/releases/tag/v0.0.0-alpha01). Hereafter, we will manage about its issues over there.

**Comment by heldersepu** [comment]
It will be nice if the Prig ILSpy plug-in was included with the install of Prig.
That will significantly simplify the step where we have to Modify Stub Settings

**Comment by urasandesu** [comment]
Umm... I don't like increasing dependencies between the packages that can run as an independent package. I guess that it will cause the side-effect that isn't good -- an increase in installation time, a problem caused by complex dependency and so on. For example, "It is unnecessary if a user might want to just write test code using the Indirection Stubs that are already prepared." or "What will happen if a user has already installed ILSpy?"

By the way, [the installation step for Prig ILSpy plug-in](https://github.com/urasandesu/ILSpy.GetPrigIndirectionStubSetting.Plugin#installation) is simple enough, isnt't it? :sweat_smile: Because you just execute the command `cinst ilspy.getprigindirectionstubsetting.plugin -y` to achieve it.

**Comment by heldersepu** [comment]
Most people stick with the Microsoft Fakes because their simplicity, even if it cost.
The step 3 Edit Prig Indirection Settings create a lot of friction...

**Comment by urasandesu** [comment]
Ah, would it just be that [Step 3](https://github.com/urasandesu/Prig#step-3-modify-stub-settings) should be replaced by [the step to use Prig ILSpy plug-in](https://github.com/urasandesu/ILSpy.GetPrigIndirectionStubSetting.Plugin#usage)?
