### ISSUE TITLE
Unable to return a mocked object for a mocked method

### ISSUE THREAD

**Issue by jaisondoss** [urasandesu/Prig#71]
In below legacy code i need to mock '_package.GetByName' method which should return a mocked 'Item'(PItem)
`Item componentItem = _package.GetByName(Package.ComponentName);`
Am using the below code to mock the GetByName method and return a mocked Item object. 
`PPackage.GetByNameString().Body =(@this, name) => { return new PItem(); };`
Unfortunately am unable to cast PItem to Item object as there is no inheritance involved. 

Could you please help me with the syntax to return a mocked object to a method or how to associate mocked object(PItem) to the actual object(Item). 
**Note :** I would not be able to initialize the actual Item class as the constructor is internal. 
I was able to achieve it using Shim in MSFakes by returning a ShimItem. Hope a similar behavior would be available in Prig too.

Also am unable to mock the constructor of classes.
`PPackage.StaticConstructor().Body = () => { new PPackage(); };` or
`PPackage.ConstructorEngine().Body = (@this, engine) => { new PPackage(); };` or
`PEngine.StaticConstructor().Body = () => { new PEngine(); };`
Am not sure whether am using the syntax correctly.
It would be really helpful if you could provide a guide with lot of syntax samples to get familiarize with Prig.

**Comment by urasandesu** [comment]
> Could you please help me with the syntax to return a mocked object to a method or how to associate mocked object(PItem) to the actual object(Item). 

Are you saying about the way to shim [Instance methods (for one runtime instance) in the Microsoft Fakes](https://msdn.microsoft.com/en-us/library/hh549176.aspx#BKMK_Instance_methods__for_one_instance_)?
Prig supports it by `PProxy` Prig Type. Instead of the above, you can write the following: 
```cs
PPackage.GetByNameString().Body =(@this, name) => { return new PProxyItem(); };
```
In the document, [Mocking Instance Method - CHEAT SHEET](https://github.com/urasandesu/Prig/wiki/Cheat-Sheet#mocking_instance_method) describes some examples about that. If you have used Microsoft Fakes before, [Migration From Microsoft Fakes sample](https://github.com/urasandesu/Prig/wiki/Mocking-HttpWebRequest-by-Microsoft-Fakes) is also helpful.

**Comment by urasandesu** [comment]
> Also am unable to mock the constructor of classes.
> `PPackage.StaticConstructor().Body = () => { new PPackage(); };` or
> `PPackage.ConstructorEngine().Body = (@this, engine) => { new PPackage(); };` or
> `PEngine.StaticConstructor().Body = () => { new PEngine(); };`
> Am not sure whether am using the syntax correctly.

The example that contains mocking a constructor is [Calling Original Method](https://github.com/urasandesu/Prig/wiki/Calling-Original-Method).
However, if you want to just empty them, all you have to do is to assign empty lambda expression. For example: 
```cs
PPackage.StaticConstructor().Body = () => { };
PPackage.ConstructorEngine().Body = (@this, engine) => { };
PEngine.StaticConstructor().Body = () => { };
```

**Comment by jaisondoss** [comment]
I executed the following command to create proxy for Item class but still PProxy class is not generated.
`$targets = [Tridion.ContentManager.Templating.Item].GetMembers() | ? { $_ -is [System.Reflection.MethodBase] } | ? { !$_.IsAbstract } | ? { $_.DeclaringType -eq $_.ReflectedType }
$targets | pget | clip`
Indirection command created referring to [Mocking HttpWebRequest](https://github.com/urasandesu/Prig/wiki/Mocking-HttpWebRequest-by-Microsoft-Fakes)
