### ISSUE TITLE
From VS IDE unable to successfully run multiple test projects

### ISSUE THREAD

**Issue by oldhamir** [urasandesu/Prig#94]
I've got several VS solutions each with multiple test projects that use Prig assemblies, I'm converting from Fakes, which worked fine, as I no longer work for a firm that can afford VS Ultimate :-). 

Each test project seems to have its own test adapter but in the Prig menu option there is only ever the ability to enable/disable one test adapter so only the tests using that adapter will pass when run from the VS IDE Test Explorer. E.g. if I have TestProject1 and TestProject2 then I can enable TestProject1 Adapter so that its associated tests will pass, but all tests using TestProject2 Adapter will fail. I can then switch to the TestProject2 and enable TestProject2 Adapter and its tests will pass but TestProject1's tests will fail.

I am willing to have a go at trying to make this work but could do with some pointers to save me time and effort. For instance why do you need to enable and disable test adapters in the first place? Why are there multiple test adapters? I could understand if they each used different test runners but if a solution uses one test runner then why not just have one solution wide test adapter?

**Comment by urasandesu** [comment]
Thank you for the reporting but it is possibly duplicate with #86, isn't it?

Currently, Prig is supporting to enable against one test project. This limitation is going to be gone at next release (within a few months).

**Comment by oldhamir** [comment]
Hello,

     yes, this is a duplicate of #86. I'm sorry for creating the duplicate, I
did have a look through the issues both outstanding and fixed before posting #94
but for some reason I didn't dive into the details of #86, I guess I need to
take more care in future :-).

I am willing to try and help sort this issue if you need help as it's a bit of a
pain for me, I notice that you've posted some hints in the issue details.


Again, sorry for the inconvenience, Ian
